# Generated by Django 5.1.2 on 2024-12-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="was_chosen",
            field=models.IntegerField(default=0),
        ),
    ]
